"""AI Calls page — Bland AI phone call management."""
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import streamlit as st
import pandas as pd
from utils import api_client

st.set_page_config(page_title="AI Calls", page_icon="📞", layout="wide")
st.title("📞 AI Phone Calls")
st.caption("AI-powered outbound calls via Bland AI · Scripts generated by Groq Llama-3")
st.divider()

# ── Stats ─────────────────────────────────────────────────────────────────────
try:
    stats = api_client.call_stats()
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("📞 Total Calls",     stats.get("total", 0))
    c2.metric("✅ Completed",       stats.get("completed", 0))
    c3.metric("⏳ Initiated",       stats.get("initiated", 0))
    c4.metric("❌ Failed",          stats.get("failed", 0))
except Exception as e:
    st.error(f"Stats unavailable: {e}")

st.divider()

# ── Initiate New Call ─────────────────────────────────────────────────────────
st.subheader("📞 Initiate New AI Call")

try:
    companies = api_client.list_companies(limit=500)
    company_map = {f"{c['name']} (#{c['id']})": c for c in companies}
except Exception:
    companies = []
    company_map = {}

if not companies:
    st.warning("⚠️ No companies found. Add a company first in the Companies page.")
else:
    with st.form("new_call_form"):
        col1, col2 = st.columns(2)

        with col1:
            company_label = st.selectbox("Select Company *", list(company_map.keys()))
            selected_company = company_map.get(company_label, {})

            phone = st.text_input(
                "Phone Number *",
                value=selected_company.get("phone", ""),
                placeholder="+1 234 567 8900",
                help="Include country code e.g. +91XXXXXXXXXX"
            )
            voice = st.selectbox("AI Voice", ["maya", "ryan", "adriana", "derek", "evelyn"])

        with col2:
            max_dur = st.slider("Max Duration (minutes)", 2, 30, 12)
            use_custom = st.checkbox("Write custom call task (overrides AI-generated script)")

        custom_task = ""
        if use_custom:
            custom_task = st.text_area(
                "Custom Call Task / Script",
                height=120,
                placeholder="You are a sales representative calling on behalf of ProPlumb Supply…",
            )
        else:
            st.info("🤖 Groq Llama-3 will auto-generate a call script based on company data and notes.")

        submitted = st.form_submit_button("📞 Initiate Call", use_container_width=True, type="primary")

        if submitted:
            if not phone.strip():
                st.error("Phone number is required.")
            elif not phone.startswith("+"):
                st.error("Phone must include country code (e.g. +91...)")
            else:
                with st.spinner("Connecting to Bland AI…"):
                    try:
                        payload = {
                            "company_id": selected_company["id"],
                            "phone_number": phone.strip(),
                            "voice": voice,
                            "max_duration": max_dur,
                        }
                        if custom_task.strip():
                            payload["custom_task"] = custom_task.strip()

                        result = api_client.initiate_call(payload)
                        st.success(f"✅ Call initiated! ID #{result['id']} · Bland ID: {result.get('bland_call_id','N/A')}")
                        st.balloons()
                    except Exception as e:
                        st.error(f"❌ Call failed: {e}")

st.divider()

# ── Call History ──────────────────────────────────────────────────────────────
st.subheader("📋 Call History")

col_filter1, col_filter2 = st.columns([2, 1])
with col_filter2:
    status_filter = st.selectbox("Filter by status", ["All", "initiated", "completed", "failed"])

try:
    status_param = None if status_filter == "All" else status_filter
    calls = api_client.list_calls(status=status_param)
except Exception as e:
    st.error(f"Cannot load calls: {e}")
    st.stop()

if not calls:
    st.info("No calls yet. Initiate your first AI call above.")
    st.stop()

# Build display dataframe
df = pd.DataFrame(calls)

# Company name lookup
cid_to_name = {c["id"]: c["name"] for c in companies}
if "company_id" in df.columns:
    df["company"] = df["company_id"].apply(lambda x: cid_to_name.get(x, f"#{x}"))

display_cols = ["id", "company", "phone_number", "status", "duration", "created_at"]
available = [c for c in display_cols if c in df.columns]
st.dataframe(df[available], use_container_width=True, hide_index=True)

st.divider()

# ── Call Detail ───────────────────────────────────────────────────────────────
st.subheader("🔍 Call Detail & Sync")

call_options = {f"#{c['id']} — {cid_to_name.get(c['company_id'], '?')} ({c['status']})": c["id"] for c in calls}
selected_call_label = st.selectbox("Select call", list(call_options.keys()))
selected_call_id    = call_options[selected_call_label]
selected_call       = next((c for c in calls if c["id"] == selected_call_id), {})

col_a, col_b, col_c = st.columns(3)
col_a.metric("Status",   selected_call.get("status", "—"))
col_b.metric("Duration", f"{selected_call.get('duration', 0) or 0}s")
col_c.metric("Bland ID", selected_call.get("bland_call_id", "—") or "—")

if selected_call.get("recording_url"):
    st.markdown(f"🎙️ [Listen to Recording]({selected_call['recording_url']})")

if st.button("🔄 Sync Status from Bland AI"):
    with st.spinner("Fetching from Bland AI…"):
        try:
            updated = api_client.sync_call(selected_call_id)
            st.success(f"Synced! Status: **{updated['status']}** | Duration: {updated.get('duration',0)}s")
            if updated.get("summary"):
                st.subheader("📝 AI Call Summary")
                st.markdown(updated["summary"])
            st.rerun()
        except Exception as e:
            st.error(f"Sync failed: {e}")

if selected_call.get("transcript"):
    with st.expander("📜 Full Transcript"):
        st.text_area("Transcript", selected_call["transcript"], height=300, disabled=True)

if selected_call.get("summary"):
    with st.expander("📝 AI Summary (Groq)"):
        st.markdown(selected_call["summary"])

# ── AI Call Script Generator ──────────────────────────────────────────────────
st.divider()
st.subheader("🤖 Generate Call Script (Preview)")
st.caption("Use Groq Llama-3 to preview a call script before dialling")

if companies:
    preview_company_label = st.selectbox("Company for script preview", list(company_map.keys()), key="script_preview_select")
    preview_company = company_map.get(preview_company_label, {})

    if st.button("✨ Generate Script Preview"):
        with st.spinner("Generating with Groq Llama-3…"):
            try:
                result = api_client.ai_call_script({
                    "company_name":  preview_company.get("name", ""),
                    "contact_name":  preview_company.get("contact_name", "the decision maker"),
                    "industry":      preview_company.get("industry", ""),
                    "notes":         preview_company.get("notes", ""),
                })
                st.subheader("Generated Script")
                st.text_area("Script", result.get("script", ""), height=300, disabled=True)
            except Exception as e:
                st.error(f"Script generation failed: {e}")
